<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="yaml_diagram" nsURI="http://www.example.org/yaml_diagram" nsPrefix="yaml_diagram">
  <eClassifiers xsi:type="ecore:EClass" name="Object"/>
  <eClassifiers xsi:type="ecore:EClass" name="Array"/>
  <eClassifiers xsi:type="ecore:EClass" name="Value" eSuperTypes="#//Object #//Array #//Data">
    <eStructuralFeatures xsi:type="ecore:EReference" name="key" eType="#//Key" eOpposite="#//Key/value"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Key">
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" eType="#//Value"
        eOpposite="#//Value/key"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Data">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="strategy" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
  </eClassifiers>
</ecore:EPackage>
